[package]
name = "security_camera"
version = "0.1.0"
edition = "2021"

[dependencies]
rscam = "0.5"
warp = "0.3"
tokio = { version = "1", features = ["full"] }
futures-util = "0.3"
image = "0.23.14"

[profile.dev]
opt-level = 2  # Or 2 for a balance between speed and optimization
incremental = true